### ISSUE TITLE
investigate dynamic linking for zlib, sqlite

### ISSUE THREAD

**Issue by lneely** [lneely/pcloudcc-lneely#13]
What are the pros and cons of dynamically linking ~mbedtls,~ zlib, and sqlite?

**Comment by lneely** [comment]
Created a different ticket for mbedtls, may decide to migrate to something like openssl or libressl.

**Comment by lneely** [comment]
Pros: smaller code base, delegate security patching and bug fixes to upstream, overall less work.

Possible con: dependency hell. Could consider packaging in a container/sandbox for distributions that don't supply a needed library.

So far, pros outweigh cons. Leaning yes on this.

**Comment by lneely** [comment]
mbedtls is a heavy lift, zlib and sqlite not so much.  closing this ticket since zlib and sqlite are now dynamically linked. creating a different ticket for mbedtls.

**Comment by dargmuesli** [comment]
Should the README specify that, e.g. on Ubuntu, `libsqlite3-dev` should be installed?

**Comment by lneely** [comment]
@dargmuesli thanks! Added it to the README. :).
