### ISSUE TITLE
Create an AUR package

### ISSUE THREAD

**Issue by coxackie** [lneely/pcloudcc-lneely#26]
As the title suggests. We discussed about this at the AUR package of the official unmaintained repo. Just leaving it here as a soft reminder.

**Comment by coxackie** [comment]
Just saw an issue was open before. It is closed, but I don;t see an AUR package. Did you abandon the idea, @lneely?

**Comment by lneely** [comment]
> Just saw an issue was open before. It is closed, but I don;t see an AUR package. Did you abandon the idea, @lneely?

Nah, just been sidetracked with other things. I'll get to it sometime.

**Comment by coxackie** [comment]
> > Just saw an issue was open before. It is closed, but I don;t see an AUR package. Did you abandon the idea, @lneely?
> 
> Nah, just been sidetracked with other things. I'll get to it sometime.

ok, than, if you don;t mind we can keep this ticket open?

**Comment by lneely** [comment]
Sure. I don't remember for sure but I think my only intent was to separate distribution packaging from the work here. No current plan to maintain a PKGBUILD or any other packaging concerns in this repo, but also no reason not to keep the ticket open since AUR package was part of my plan.

**Comment by lneely** [comment]
@coxackie The AUR package is published.

https://aur.archlinux.org/packages/pcloudcc-lneely
