### ISSUE TITLE
Selective sync

### ISSUE THREAD

**Issue by coxackie** [lneely/pcloudcc-lneely#28]
Feature request: add a way to provide selective sync of folders locally. This is going to be a nightmare most probably, but _if_ it can be handled it will be a game-changer.

Some notes: at the moment, this functionality is only provided by the horrid electron UI app. However, once set up there, the cli seems to be able to take care of it later on. Therefore, it should be doable. Both the cli and the electron app read the `data.db` file in the local `$HOME/.pcloud` folder. Evidently, this is an sql database; if deciphered, this can be possible.

There is already a lot of ground work here: https://github.com/pcloudcom/console-client/issues/23. If the dev is ready to take on the challenge, we may be able to get rid of the electron app altogether.

**Comment by lneely** [comment]
I like this idea, thanks! I haven't forgotten about this project, I've just been going through the bodily punishment of resuming BJJ after a long hiatus (I dd promise haphazard and inconsistent maintenance after all). Once I get through that, I'll have a look at this. :beers:

**Comment by lneely** [comment]
Discovered several functions suggesting upcoming features that never got released.  One of them was `list_sync_folders`. I was able to get the API call to work, but there was no path to get the callback response back to the client. I've implemented this path, and am working through some problems with the size of the callback response data. Once that's fixed, I will have a functioning "list sync folders" command in the CLI.

**Comment by lneely** [comment]
I now have a working `list_sync_folders` function.  You were right, this is not easy.

**Comment by coxackie** [comment]
You are doing the work of God...

**Comment by lneely** [comment]
Meh. It's just fun. Now I have a working `add_sync_folder` function. The code is a fucking mess, but I'll fix that stuff later. For now, I'm just happy the behavior is correct.

**Comment by lneely** [comment]
All core functionality implemented. Cleaning up, then testing. When I'm "reasonably" confident everything still works, will merge into main. :beers:

**Comment by lneely** [comment]
@coxackie Allright buddy, we're doing it live. Merged into `main`. Good luck!
