### ISSUE TITLE
syncadd: specify sync type

### ISSUE THREAD

**Issue by lneely** [lneely/pcloudcc-lneely#62]
Currently the program only supports adding sync folders with full synchronization (2-way). Would be better to be able to specify the type of synchronization (upload-only, download-only, full).

Depends on:
- #60

**Comment by coxackie** [comment]
This sounds very exciting, but I want to exercise a bit of caution here.

The database file `~/.pcloud/data.db` can be accessed by both `pcloudcc` and the (horrific) official electron client. Right now, the two programs (cli and electron) can happily co-exist and share the database file (although of course they cannot be active at the same time). In the past, I had to use the electron client time to time, for example to set syncing folders (which can now be covered by the cli). I can imagine other users, or use-cases, where both cli and electron are present in the system. Therefore, I would like to suggest in keeping compatibility of what happens in the database with respect to access from both tools.

The above are of course a remark that is not specific for this issue, but I did not notice (although I did not search a lot) a method to create one-way sync from the electron app. Therefore, I am not sure how this may affect the electron client.

**Comment by lneely** [comment]
This makes sense, and it could be that the field is only there to support different functionality (backup? I suspect from my last read of the code that "backups" are a special case of "sync folders").

For now I will close this ticket as "won't fix", since I couldn't find any evidence that the electron client has this ability.
