### ISSUE TITLE
AUR PKGBUILD suggestions

### ISSUE THREAD

**Issue by coxackie** [lneely/pcloudcc-lneely#66]
I have a couple of suggestion for the `pcloudcc-lneely` AUR package - look below. First of all, there is an addition
```
provides=("pcloudcc")
conflicts=("pcloudcc-git")
```
in paricular in order to remove `pcloudcc-git` if present and replace it with `pcloudcc-lneely`, as well as the split
```
depends=(zlib fuse2 mbedtls2 sqlite)
makedepends=(boost udev)
```
of dependencies in runtime and build ones.

The whole updated PKGBUILD follows:
```
pkgname=pcloudcc-lneely
pkgver=20240825T2000Z
pkgrel=2
epoch=0
pkgdesc="pcloudcc-lneely is a simple linux console client for pCloud cloud storage, forked from github.com/pcloudcom/console-client and independently maintained."
arch=('x86_64')
provides=("pcloudcc")
conflicts=("pcloudcc-git")
url="https://github.com/lneely/pcloudcc-lneely"
license=(BSD-3-Clause)
depends=(zlib fuse2 mbedtls2 sqlite)
makedepends=(boost udev)

source=("$pkgname-$pkgver.tar.gz::https://codeload.github.com/lneely/pcloudcc-lneely/tar.gz/refs/tags/$pkgver")
sha256sums=('a7e21fc03e9fb588949d64350fee69c7d7200eb33a294526c910b0020b5120be')

build() {
    cd "pcloudcc-lneely-$pkgver"
    make
}

package() {
    cd "pcloudcc-lneely-$pkgver"
    install -d $pkgdir/usr/bin
    install -m 755 pcloudcc $pkgdir/usr/bin/pcloudcc
}
```

**Comment by lneely** [comment]
Looks good, I will make the changes. Also saw your comment on AUR, looks like this proposal addresses that as well.

**Comment by coxackie** [comment]
Great. I also just updated `pkgrel=2` above, in case you update it before the next version update of your package.

**Comment by coxackie** [comment]
naive question, without having had time to look through the code: are `mbedtls2` and `sqlite` runtime dependencies? or just used in building? Just asking because in the official repo these were not mentioned. (I can see in a PR linking to system `mbedtls2`, but not sure if this is only for building.)

**Comment by lneely** [comment]
> naive question, without having had time to look through the code: are `mbedtls2` and `sqlite` runtime dependencies? or just used in building? Just asking because in the official repo these were not mentioned. (I can see in a PR linking to system `mbedtls2`, but not sure if this is only for building.)

These are runtime dependencies.  `sqlite` is needed to manage the database located at `~/.pcloud/data.db`, and `mbedtls2` is used for cryptographic operations like SSL handshakes, locking and unlocking the crypto folder, etc.

The reason `mbedtls2` and `sqlite` aren't mentioned is because the official repo brings the entire source for both into its source tree under `lib/`. I felt this led to unnecessary build complexity, so updated the build process to use the system libraries. In the process, I upgraded the code to use mbedtls to 2.x (they used 1.x which has been EOL for years).

**Comment by lneely** [comment]
Done!

**Comment by coxackie** [comment]
> > naive question, without having had time to look through the code: are `mbedtls2` and `sqlite` runtime dependencies? or just used in building? Just asking because in the official repo these were not mentioned. (I can see in a PR linking to system `mbedtls2`, but not sure if this is only for building.)
> 
> These are runtime dependencies. `sqlite` is needed to manage the database located at `~/.pcloud/data.db`, and `mbedtls2` is used for cryptographic operations like SSL handshakes, locking and unlocking the crypto folder, etc.
> 
> The reason `mbedtls2` and `sqlite` aren't mentioned is because the official repo brings the entire source for both into its source tree under `lib/`. I felt this led to unnecessary build complexity, so updated the build process to use the system libraries. In the process, I upgraded the code to use mbedtls to 2.x (they used 1.x which has been EOL for years).

thanks a lot for settling this! Maybe you can also consider moving to `fuse3` - maybe a new ticket for this should be opened in time.
