### ISSUE TITLE
Support device validation

### ISSUE THREAD

**Issue by lneely** [lneely/pcloudcc-lneely#80]
Extends #79.

Users have reported that, when running on a device that is not already known to pcloud.com, `pcloudcc` is failing to connect to the services. Observed behavior is described in tickets #27 and #72. While this is expected behavior, not all users are running `pcloudcc` on devices on a local machine with web browsing capabilities.

TODO:
- Investigate API support for device validation
- If possible, implement device validation in `pcloudcc`
- Consider OAuth2.

**Comment by lneely** [comment]
I've contacted pCloud's support team regarding this ticket.  They have confirmed that the API does not support device validation.  It seems the best we can do for these cases are to consider them "non standard" and use the workarounds in the readme. 

Any other suggestions are of course welcome, but for now I am closing this ticket since it is "resolved" to the extent that it can be.

**Comment by svefro** [comment]
What is the point of a cli-client if it needs a gui to work? sigh.

Can't you implement entering the validation code in the terminal?

I made a small simple sh script that clones the cli. builds it and runns it. This was ment to be used on headles vm's to exchange files and do backups. but when it needs a gui it is to much work.

Also there is no error shown in the console when the device is "un-trusted"

**Comment by lneely** [comment]
Understandable. If this were under my control, then it would already be done.
